### ISSUE TITLE
Mismatched team names

### ISSUE THREAD

**Issue by kokarn** [theseal/hockey-mchockeyface#10]
For some horrible reason the data-source we use don't use the correct names published by SHL.

The source for the correct names is this
http://www.shl.se/om-shl/press-media#mediaguide

Should this be something we change when we start using the API instead perhaps?

**Comment by theseal** [comment]
Impressive!
Its always good when the official data-source mismatched the names or don't always use the full name…

This is the errors I have found
* _Djurgården_ -> _Djurgården Hockey_
* _Frölunda HC_ -> _Frölunda Indians_

**Comment by theseal** [comment]
Fixed by #23.
