### ISSUE TITLE
Improve team handling

### ISSUE THREAD

**Issue by kokarn** [theseal/hockey-mchockeyface#27]
Right now https://hockey-mchockeyface.herokuapp.com/calendar?team=lif works but will return an empty list which is probably not ideal.

Also, https://hockey-mchockeyface.herokuapp.com/calendar?team=kokarn works. Should probably return a 404

**Comment by theseal** [comment]
Not sure if I should create another issue or re/miss-use this one…

If upstream change the identifier of a team to something we can't match we return an empy ical file. This is not ideal… 😜
