### ISSUE TITLE
DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by theseal** [theseal/hockey-mchockeyface#3]

**Comment by kokarn** [comment]
Maybe add some context?

**Comment by theseal** [comment]
Happens sometimes™ when receiving the first request. 
I guess that its something with the download part. Race condition?

**Comment by kokarn** [comment]
Yeah probably, I'll have a look if I can

**Comment by theseal** [comment]
Fixed by #23.
