### ISSUE TITLE
Add Väsby

### ISSUE THREAD

**Issue by kokarn** [theseal/hockey-mchockeyface#30]
https://www.hockeyallsvenskan.se/artikel/qnd5akdfy-1el1/vasby-valkomna-till-hockeyallsvenskan

**Comment by theseal** [comment]
https://twitter.com/theseal/status/1291056674627891202

**Comment by theseal** [comment]
Enligt stats.swehockey.se förkortades Väsby som VSB tidigare säsong, troligen samma i Hockeyallsvenskan. 
https://stats.swehockey.se/Players/Statistics/ScoringLeaders/10403
